### ISSUE TITLE
Slicer too big

### ISSUE THREAD

**Issue by wisepotato** [microsoft/powerbi-visuals-timeline#64]
Hi, great slicer and I use it daily! I have a request , it takes up about 25% of the page , and I would like some control for the size. 

It's great but its so big! I would also like a recommendation as to where I could change some of this to make a custom version myself.

**Comment by PesceJonathan** [comment]
I have made modifications to the visual, but I have not published the changes. The main change I made was to reduce the size of the visual. Here is an example of what the visual would look like:

![image](https://user-images.githubusercontent.com/31356845/59919925-1b0e4200-9429-11e9-97f5-9fdb75bd0148.png)

If you would like to use the visual with these modifications, I can send you the visual to use.

**Comment by wisepotato** [comment]
I would actually! Like the big part of what i want is a bit more control and less emlty spave so this is perfect

**Comment by PesceJonathan** [comment]
I will host the code on GitHub and send you the link tonight, sorry for the delay.

**Comment by wisepotato** [comment]
you dont owe me anything, I just like it very much :)

**Comment by PesceJonathan** [comment]
Here is the link to the repo, I am not on the right computer to compile it, but if you are unable to I can compile it and send you the pbiviz file instead: https://github.com/PesceJonathan/PowerBi-TimeSlicer 

Enjoy, and feel free to leave any feedback on the repo, I plan on continuing to work on it so feedback is appreciated.

**Comment by mdc52676** [comment]
Is it possible to get a copy of the PBIVIZ for this slicer?

**Comment by mdc52676** [comment]
Is it possible to get a copy of the PBIVIZ for this slicer?

**Comment by mdc52676** [comment]
Is it possible to get a copy of the PBIVIZ for this slicer?

**Comment by mdc52676** [comment]
Is it possible to get a copy of the PBIVIZ for this slicer?

**Comment by mdc52676** [comment]
Is it possible to get a copy of the PBIVIZ for this slicer?

**Comment by mdc52676** [comment]
Is it possible to get a copy of the PBIVIZ for this slicer?

**Comment by mdc52676** [comment]
Is it possible to get a copy of the PBIVIZ for this slicer?

**Comment by mdc52676** [comment]
Is it possible to get a copy of the PBIVIZ for this slicer?

**Comment by PesceJonathan** [comment]
I have not worked with the visual since I created it a long time ago so it has not been updated to work with the new standards. I will probably get to fixing it eventually but at the moment I am swamped. 

If you want to help just post any bugs you find on GitHub issues and I will try to fix them first chance I get. 


[dist.zip](https://github.com/microsoft/powerbi-visuals-timeline/files/5066399/dist.zip)

**Comment by mdc52676** [comment]
Thanks for the response. I am not familiar with how to create the PBIVIZ file from what you have posted on GITHUB but if I figure it out I will take a look.



Thanks,

Michael Carapellotti
Assistant Vice President
Business Intelligence and Technology Solutions

The Hartford Steam Boiler Inspection and Insurance Company

Bay Colony Executive Park
595 East Swedesford Road
Wayne, PA 19087
Telephone:  (484) 582-1511
Mobile: (215) 601-1110
Facsimile:   (800) 298-4083

Michael_Carapellotti@hsb.com<mailto:Michael_Carapellotti@hsb.com>

hsb.com<https://www.hsb.com/>
[HSB IIC]




[linkedin]<https://www.linkedin.com/company/hsb>
[twitter]<https://twitter.com/HtfdSteamBoiler>
[facebook]<https://www.facebook.com/HartfordSteamBoiler>

IMPORTANT NOTICE:
This email (including any attachments) contains confidential and proprietary information that is intended only for the individual or entity designated above. If you are not the intended recipient, please be aware that any use, review, distribution, reproduction, copying, or action taken in reliance upon this email is strictly prohibited. If you received this email in error, please notify the sender immediately, and permanently delete and destroy this email and any hard and electronic copies thereof. Although we have taken reasonable precautions to reduce the risk of transmitting software viruses, it is the responsibility of the recipient to ensure that this email is virus-free. The Hartford Steam Boiler Inspection and Insurance Company (including its subsidiaries and affiliates) disclaims any and all liability for any loss or damage caused by this email whether due to viruses, interference, interception, data corruption, unapproved access, misrepresentation, or otherwise.

**Comment by PesceJonathan** [comment]
You don't need to create the pbiviz file, it is included within the ZIP file that I attached. If you are unable to extract it from there, I can send it to your directly to your email.

**Comment by EugeneElkin** [comment]
Hi guys,

There are several relatively new options that help to reduce visual size.
1. Labels -> Display All -> switch to off -- it will show only labels regarding selected granularity, but not all the chain
2. Granularity -> switch to off -- will remove granularity picker, but users will be able to pick granularity through format panel
3. Range Header -> switch to off -- will remove info (labels) about begin and end dates
Then you need only to reduce size of the visual so, result will be the following 

![image](https://user-images.githubusercontent.com/7499112/105347665-42765380-5bf8-11eb-952c-df250bd8e0b0.png)

Kind Regards

**Comment by mdc52676** [comment]
Are you commenting on the production version through the Power BI store where these changes have been made?

**Comment by EugeneElkin** [comment]
Yep, these changes have to be on prod. I will check lately.
